import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { email, csvData, fileName } = await request.json();

    // Dynamic import of nodemailer to avoid webpack issues
    const nodemailer = await import("nodemailer");

    // Create transporter using Gmail
    const transporter = nodemailer.default.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_PASS,
      },
    });

    // Create formatted HTML email content
    const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <h2 style="color: #333; text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px;">
        🎯 TOPSIS Analysis Results
      </h2>
      
      <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <h3 style="color: #000; margin-top: 0;">Analysis Complete!</h3>
        <p style="color: #333; font-size: 16px; line-height: 1.6;">
          Your TOPSIS (Technique for Order Preference by Similarity to Ideal Solution) 
          multi-criteria decision analysis has been successfully completed.
        </p>
        
        <div style="background: white; padding: 15px; border-radius: 5px; margin: 15px 0; border-left: 4px solid #000;">
          <strong>📎 Attachment:</strong> ${fileName ? `result_${fileName}` : "topsis_results.csv"}
        </div>
        
        <p style="color: #666; font-size: 14px;">
          The attached CSV file contains your complete analysis results including:
        </p>
        <ul style="color: #666; font-size: 14px;">
          <li>Original data with identifiers</li>
          <li>Calculated TOPSIS scores (0-1 scale)</li>
          <li>Final rankings (1 = best alternative)</li>
        </ul>
      </div>
      
      <div style="text-align: center; margin: 30px 0;">
        <p style="color: #333; font-size: 16px;">
          Thank you for using <strong>TOPSIS Calculator</strong>!
        </p>
        <p style="color: #666; font-size: 14px;">
          Developed by <strong>Surya Kant Tiwari</strong>
        </p>
        <a href="https://github.com/SuryaKTiwari11/TOPSIS" style="color: #000; text-decoration: none; font-weight: bold;">
          🔗 View on GitHub
        </a>
      </div>
      
      <div style="border-top: 1px solid #ddd; padding-top: 15px; margin-top: 30px; font-size: 12px; color: #888; text-align: center;">
        This email was automatically generated by the TOPSIS Web Application.
      </div>
    </div>
    `;

    // Create email options
    const mailOptions = {
      from: {
        name: "TOPSIS Calculator",
        address: process.env.GMAIL_USER!,
      },
      to: email,
      subject: "🎯 Your TOPSIS Analysis Results - Ready for Download",
      text: `TOPSIS Analysis Results\n\nYour multi-criteria decision analysis has been completed!\n\nFile: ${fileName}\n\nThe attached CSV file contains your complete analysis results including original data, TOPSIS scores, and final rankings.\n\nThank you for using TOPSIS Calculator!\nDeveloped by Surya Kant Tiwari\n\nGitHub: https://github.com/SuryaKTiwari11/TOPSIS`,
      html: htmlContent,
      attachments: [
        {
          filename: fileName ? `result_${fileName}` : "topsis_results.csv",
          content: csvData,
          contentType: "text/csv",
        },
      ],
    };

    // Send email
    const info = await transporter.sendMail(mailOptions);

    console.log("Email sent successfully:", info.messageId);

    return NextResponse.json({
      success: true,
      message: `Results sent to ${email}`,
      messageId: info.messageId,
    });
  } catch (error) {
    console.error("Email sending failed:", error);

    // Return more specific error information
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error occurred";

    return NextResponse.json(
      {
        success: false,
        message: `Failed to send email: ${errorMessage}`,
        error: errorMessage,
      },
      { status: 500 },
    );
  }
}
